import test from 'node:test';import assert from 'node:assert/strict';import {createMatch,act,active,damage,validTeam,botAction} from '../src/engine.js';
const teams=[['ember','brook','moss'],['pebble','spore','mist']];
test('unique team and energy cap',()=>{assert.equal(validTeam(['ember','ember','moss']),false);let s=createMatch(teams,0);for(let i=0;i<8;i++){s=act(s,s.turn,{type:'guard'});assert.ok(s.players.every(p=>p.energy>=0&&p.energy<=6));}});
test('turn ownership, switching quota, dead cards',()=>{let s=createMatch(teams,0);assert.throws(()=>act(s,1,{type:'basic'}));for(let i=0;i<3;i++){s=act(s,0,{type:'switch',index:(s.players[0].active+1)%3});s=act(s,1,{type:'guard'});}assert.equal(s.players[0].switches,0);assert.throws(()=>act(s,0,{type:'switch',index:0}));s.players[0].team[1].hp=0;assert.throws(()=>act(s,0,{type:'switch',index:1}));});
test('special cooldown includes reserves and lasts two owner turns',()=>{let s=createMatch([['spark','brook','moss'],teams[1]],0);s=act(s,0,{type:'special'});assert.equal(s.players[0].team[0].cooldown,3);s=act(s,1,{type:'basic'});assert.equal(s.players[0].team[0].cooldown,2);assert.throws(()=>act(s,0,{type:'special'}));s=act(s,0,{type:'switch',index:1});s=act(s,1,{type:'basic'});assert.equal(s.players[0].team[0].cooldown,1);s=act(s,0,{type:'basic'});s=act(s,1,{type:'basic'});assert.equal(s.players[0].team[0].cooldown,0);});
test('shield before HP, guard and elements',()=>{let s=createMatch(teams,0);active(s,1).shield=40;active(s,1).status.shield=2;const hp=active(s,1).hp;s=act(s,0,{type:'basic'});assert.equal(active(s,1).hp,hp);assert.ok(active(s,1).shield<40);const a={id:'ember',status:{}},d={id:'moss',status:{},guard:false};assert.equal(damage(a,d,1).factor,1.25);const amount=damage(a,d,1).amount;d.guard=true;assert.ok(damage(a,d,1).amount<=Math.ceil(amount/2));});
test('status refresh, expiry, reserve damage and stun',()=>{let s=createMatch(teams,0);const u=s.players[0].team[1];u.status.poison=1;const hp=u.hp;s=act(s,0,{type:'basic'});assert.ok(s.players[0].team[1].hp<hp);assert.equal(s.players[0].team[1].status.poison,undefined);active(s,1).status.stun=1;const targetHP=active(s,0).hp;s=act(s,1,{type:'special'});assert.equal(active(s,0).hp,targetHP);assert.equal(active(s,1).status.stun,undefined);});
test('forced replacement is free and preserves next turn',()=>{let s=createMatch(teams,0);active(s,1).hp=1;s=act(s,0,{type:'basic'});assert.equal(s.pending,1);const before=structuredClone(s.players[1]);s=act(s,1,{type:'replace',index:1});assert.equal(s.turn,1);assert.equal(s.players[1].switches,before.switches);assert.equal(s.players[1].energy,before.energy);});
test('full bot matches terminate legally',()=>{for(let run=0;run<20;run++){let s=createMatch(teams,run%2),n=0;while(s.winner===null&&n++<500){const p=s.pending??s.turn;s=act(s,p,botAction(s,p));assert.ok(s.players.every(p=>p.energy>=0&&p.switches>=0));}assert.notEqual(s.winner,null);}});

test('draw when attack and owner status processing eliminate both teams',()=>{let s=createMatch(teams,0);s.players[0].team.forEach(u=>{u.hp=1;u.status.burn=1;});s.players[1].team.forEach(u=>u.hp=0);active(s,1).hp=1;s=act(s,0,{type:'basic'});assert.equal(s.winner,'draw');assert.equal(s.pending,null);});
test('zero energy cannot guard, refresh does not stack, regen and boost expire',()=>{let s=createMatch(teams,0);s.players[0].energy=0;assert.throws(()=>act(s,0,{type:'guard'}));assert.throws(()=>act(s,0,{type:'special'}));const u=active(s,0);u.hp=50;u.status.regen=2;u.status.boost=2;s=act(s,0,{type:'basic'});assert.equal(active(s,0).status.regen,1);assert.ok(active(s,0).hp>50);s=act(s,1,{type:'guard'});s=act(s,0,{type:'basic'});assert.equal(active(s,0).status.regen,undefined);assert.equal(active(s,0).status.boost,undefined);});
import {matchSummaryHTML} from '../src/summary.js';
test('summary damage counts actual HP and shields without overkill',()=>{let s=createMatch(teams,0);active(s,1).hp=2;active(s,1).shield=3;active(s,1).status.shield=2;s=act(s,0,{type:'basic'});const stats=s.players[0].team[0].stats;assert.equal(stats.damage,5);assert.equal(stats.hpDamage,2);assert.equal(stats.shieldDamage,3);assert.equal(stats.kos,1);assert.equal(s.players[1].team[0].stats.taken,5);assert.equal(s.players[0].team[1].stats.damage,0);});
test('burn and poison credit original caster while target is reserved; refresh changes caster',()=>{let s=createMatch(teams,0);s=act(s,0,{type:'special'});s=act(s,1,{type:'basic'});s=act(s,0,{type:'special'});const direct=s.players[0].team[0].stats.damage;s=act(s,1,{type:'switch',index:1});assert.equal(s.players[0].team[0].stats.damage,direct+9);assert.equal(s.players[1].team[0].stats.taken,direct+9);s=act(s,0,{type:'guard'});s=act(s,1,{type:'guard'});assert.equal(s.players[0].team[0].stats.damage,direct+18);assert.equal(s.players[1].team[0].statusSources.burn,undefined);let t=createMatch([['spore','ember','moss'],teams[1]],0);t=act(t,0,{type:'special'});const u=t.players[1].team[0];u.statusSources.poison={player:0,id:'ember'};t=act(t,1,{type:'guard'});assert.equal(t.players[0].team[1].stats.damage,7);});
test('healing credits only actual recovery and draw/escaped names render correctly',()=>{let s=createMatch([['moss','ember','brook'],teams[1]],0);active(s,0).hp=138;s=act(s,0,{type:'special'});assert.equal(s.players[0].team[0].stats.healing,2);s.winner='draw';const html=matchSummaryHTML(s,['<A>','B']);assert.ok(html.includes('&lt;A&gt;'));assert.ok(html.includes('เสมอ'));assert.ok(html.includes('DMG'));const newMatch=createMatch(teams,0);assert.ok(newMatch.players.every(p=>p.team.every(u=>Object.values(u.stats).every(n=>n===0))));});
import {cards,elementFactor,elementWins} from '../src/cards.js';
test('four element cycle wins, loses, and neutral across all 16 matchups',()=>{const cycle=['fire','earth','wind','water'];assert.deepEqual(elementWins,{fire:'earth',earth:'wind',wind:'water',water:'fire'});for(let i=0;i<4;i++){assert.equal(cards.filter(c=>c.element===cycle[i]).length,2);for(let j=0;j<4;j++){assert.equal(elementFactor(cycle[i],cycle[j]),j===(i+1)%4?1.25:i===(j+1)%4?.8:1);}}});
test('element modifier increases attack and special damage and appears in battle log',()=>{const a={id:'ember',status:{}},d={id:'pebble',status:{},guard:false};for(const multiplier of [1,1.65]){const base=Math.max(1,31*multiplier-30*.5);assert.equal(damage(a,d,multiplier).amount,Math.round(base*1.25));assert.equal(damage(d,a,multiplier).factor,.8);}let s=createMatch(teams,0);s=act(s,0,{type:'basic'});assert.match(s.log.at(-1),/ชนะธาตุ \+25%/);assert.equal(s.players[0].team[0].stats.damage,20);});
