import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {once} from 'node:events';import {WebSocket} from 'ws';
class Client{constructor(ws){this.ws=ws;this.messages=[];ws.on('message',raw=>this.messages.push(JSON.parse(raw)));}send(m){this.ws.send(JSON.stringify(m));}async next(predicate,timeout=3000){const start=Date.now();while(Date.now()-start<timeout){const i=this.messages.findIndex(predicate);if(i>=0)return this.messages.splice(i,1)[0];await new Promise(r=>setTimeout(r,10));}throw Error('Timed out waiting for server');}}
async function connect(port=3011){const ws=new WebSocket(`ws://localhost:${port}/ws`);await once(ws,'open');return new Client(ws);}
test('authoritative multiplayer: duplicate, ownership, reconnect, expiry and agreement',{timeout:75000},async()=>{const server=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'3011'},stdio:['ignore','pipe','pipe']});await once(server.stdout,'data');const clients=[];try{const a=await connect();clients.push(a);a.send({type:'create',name:'A'});const session=await a.next(m=>m.type==='session');await a.next(m=>m.type==='room');const b=await connect();clients.push(b);b.send({type:'join',name:'B',code:session.code});await b.next(m=>m.type==='session');a.send({type:'ready',team:['ember','brook','moss']});b.send({type:'ready',team:['pebble','spore','mist']});const initial=await a.next(m=>m.type==='room'&&m.state);await b.next(m=>m.type==='room'&&m.state);const p=initial.state.turn,player=[a,b][p],other=[a,b][1-p];other.send({type:'action',id:'illegal',revision:0,action:{type:'basic'}});assert.match((await other.next(m=>m.type==='error')).message,/เทิร์น/);const command={type:'action',id:'repeat-1',revision:0,action:{type:'basic'}};player.send(command);const first=await a.next(m=>m.type==='room'&&m.state?.revision===1);const second=await b.next(m=>m.type==='room'&&m.state?.revision===1);assert.deepEqual(first.state,second.state);player.send(command);const duplicate=await a.next(m=>m.type==='room'&&m.state?.revision===1);assert.deepEqual(first.state,duplicate.state);a.ws.close();await b.next(m=>m.type==='room'&&!m.players[0].connected);const resumed=await connect();clients.push(resumed);resumed.send({type:'resume',code:session.code,token:session.token});await resumed.next(m=>m.type==='session');const restored=await resumed.next(m=>m.type==='room'&&m.players[0].connected);assert.deepEqual(restored.state,first.state);resumed.ws.close();const waiting=await b.next(m=>m.type==='room'&&!m.players[0].connected);assert.ok(waiting.players[0].deadline>Date.now()+59000);b.send({type:'action',id:'while-offline',revision:1,action:{type:'basic'}});assert.match((await b.next(m=>m.type==='error')).message,/รอคู่ต่อสู้/);const ended=await b.next(m=>m.type==='room'&&m.state&&m.state.winner!==null,65000);assert.equal(ended.state.winner,1);console.log('Disconnect forfeit verified after 60 seconds');}finally{clients.forEach(c=>c.ws.close());server.kill();}});


test('online server owns charge, stun interruption, switch effects and combo accounting',{timeout:15000},async()=>{
 const server=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'3012'},stdio:['ignore','pipe','pipe']});await once(server.stdout,'data');let a,b;
 try{
  a=await connect(3012);a.send({type:'create',name:'Tactical A'});const session=await a.next(m=>m.type==='session');
  b=await connect(3012);b.send({type:'join',name:'Tactical B',code:session.code});await b.next(m=>m.type==='session');
  a.send({type:'ready',team:['ember','brook','spore']});b.send({type:'ready',team:['mist','pebble','moss']});
  let s=(await a.next(m=>m.type==='room'&&m.state)).state;await b.next(m=>m.type==='room'&&m.state);
  async function step(p,action){const revision=s.revision+1;[a,b][p].send({type:'action',id:`tactics-${revision}`,revision:s.revision,action});const x=await a.next(m=>m.type==='room'&&m.state?.revision===revision);const y=await b.next(m=>m.type==='room'&&m.state?.revision===revision);assert.deepEqual(x.state,y.state);s=x.state;}
  if(s.turn===1)await step(1,{type:'guard'});
  const hp=s.players[1].team[0].hp;await step(0,{type:'special',damage:9999,hp:9999});assert.equal(s.players[1].team[0].hp,hp);assert.equal(s.players[0].team[0].charging,true);
  await step(1,{type:'special'});assert.equal(s.players[0].team[0].charging,false);assert.equal(s.players[0].team[0].status.stun,1);
  await step(0,{type:'special'});assert.equal(s.players[1].team[0].hp,hp);
  await step(1,{type:'guard'});await step(0,{type:'switch',index:1});assert.equal(s.players[1].team[0].status.wet,3);
  await step(1,{type:'guard'});await step(0,{type:'switch',index:2});assert.equal(s.players[0].switches,1);assert.equal(s.players[1].team[0].status.poison,3);
  await step(1,{type:'guard'});await step(0,{type:'basic'});assert.equal(s.players[1].team[0].status.wet,undefined);assert.ok(s.log.some(l=>l.includes('พายุสายน้ำ')));assert.ok(s.players[0].team[2].stats.damage>0);assert.equal(s.ai,null);
 }finally{a?.ws.close();b?.ws.close();server.kill();}
});
