import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {WebSocketServer,WebSocket} from 'ws';
import {createMatch,act,validTeam} from '../src/engine.js';
const rooms=new Map();
const server=http.createServer((req,res)=>{let file=path.resolve('dist','.'+decodeURIComponent(req.url.split('?')[0]));const root=path.resolve('dist');if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403).end();return;}if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(root,'index.html');if(!fs.existsSync(file)){res.writeHead(503).end('Run npm run build, or use npm run dev on port 5173');return;}const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[ext]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
const wss=new WebSocketServer({server,path:'/ws',maxPayload:8192});
function send(ws,data){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data));}
function broadcast(room){for(let i=0;i<room.players.length;i++)send(room.players[i].ws,{type:'room',code:room.code,you:i,players:room.players.map(p=>({name:p.name,ready:p.ready,connected:!!p.ws,deadline:p.deadline})),state:room.state});}
function leave(ws){if(!ws.room)return;const r=rooms.get(ws.room),p=r?.players[ws.player];if(!p||p.ws!==ws)return;p.ws=null;p.deadline=Date.now()+60000;clearTimeout(p.timer);p.timer=setTimeout(()=>{if(!p.ws){if(r.state&&r.state.winner===null){r.state.winner=1-ws.player;r.state.log.push('คู่ต่อสู้ไม่กลับมาภายใน 60 วินาที');}broadcast(r);}},60000);broadcast(r);}
wss.on('connection',ws=>{ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='create'||m.type==='join'||m.type==='resume'){if(ws.room)throw Error('คุณอยู่ในห้องแล้ว');let r;if(m.type==='create'){let code;do{code=crypto.randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));r={code,players:[],state:null};rooms.set(code,r);}else r=rooms.get(String(m.code).toUpperCase());if(!r)throw Error('ไม่พบห้อง');let i;if(m.type==='resume'){i=r.players.findIndex(p=>p.token===m.token);if(i<0)throw Error('สิทธิ์กลับเข้าห้องไม่ถูกต้อง');if(r.players[i].ws)throw Error('ผู้เล่นยังเชื่อมต่ออยู่');if(r.players[i].deadline<Date.now())throw Error('หมดเวลากลับเข้าห้อง');}else {if(r.players.length>=2)throw Error('ห้องเต็มแล้ว');i=r.players.length;r.players.push({token:crypto.randomUUID(),name:String(m.name||`นักเดินทาง ${i+1}`).slice(0,24),ready:false,team:null,seen:new Set()});}const p=r.players[i];clearTimeout(p.timer);p.ws=ws;p.deadline=null;ws.room=r.code;ws.player=i;send(ws,{type:'session',code:r.code,token:p.token});broadcast(r);return;}
const r=rooms.get(ws.room),p=r?.players[ws.player];if(!p||p.ws!==ws)throw Error('ยังไม่ได้เข้าห้อง');if(m.type==='leave'){ws.room=null;clearTimeout(p.timer);r.players.forEach(other=>send(other.ws,{type:'left'}));r.players.forEach(other=>{if(other.ws)other.ws.room=null;});rooms.delete(r.code);return;}if(m.type==='ready'){if(r.state)throw Error('แมตช์เริ่มแล้ว');if(!validTeam(m.team))throw Error('เลือกทีมสามใบไม่ซ้ำ');p.team=m.team;p.ready=true;if(r.players.length===2&&r.players.every(p=>p.ready&&p.ws))r.state=createMatch(r.players.map(p=>p.team));broadcast(r);return;}if(m.type==='rematch'){if(!r.state||r.state.winner===null)throw Error('แมตช์ยังไม่จบ');p.ready=false;p.rematch=true;if(r.players.every(p=>p.rematch&&p.ws)){r.players.forEach(p=>{p.ready=false;p.rematch=false;p.seen.clear();});r.state=null;}broadcast(r);return;}if(m.type==='action'){if(!r.state||r.players.some(p=>!p.ws))throw Error('กำลังรอคู่ต่อสู้กลับมา');if(typeof m.id!=='string'||m.id.length>80)throw Error('รหัสคำสั่งไม่ถูกต้อง');if(p.seen.has(m.id)){broadcast(r);return;}if(m.revision!==r.state.revision)throw Error('สถานะเปลี่ยนแล้ว กรุณารออัปเดต');r.state=act(r.state,ws.player,m.action);p.seen.add(m.id);broadcast(r);return;}throw Error('คำสั่งไม่ถูกต้อง');}catch(e){send(ws,{type:'error',message:e.message});}});ws.on('close',()=>leave(ws));ws.on('error',()=>{});});
setInterval(()=>{for(const [code,r] of rooms)if(r.players.every(p=>!p.ws)&&r.players.every(p=>!p.deadline||Date.now()>p.deadline+300000)){r.players.forEach(p=>clearTimeout(p.timer));rooms.delete(code);}},60000).unref();
server.listen(Number(process.env.PORT)||3001,'0.0.0.0',()=>console.log('Pocket Card Arena server: http://localhost:3001'));
