import {icon} from './icons.js';
import {tacticalIntentHTML,tacticalHUDHTML,specialButtonHTML,cardTacticsHTML,tacticsHelpHTML} from './tactical-ui.js';
import {matchSummaryHTML} from './summary.js';
import './style.css';
import {cards,byId,elements,statuses,CONFIG,elementWins,elementFactor,elementMatchupText} from './cards.js';
import {createMatch,act,active,botAction,damage} from './engine.js';
import {ArenaView} from './arena.js';
import {Online} from './online.js';
const elementHTML=element=>`${icon(elements[element][0])} ${elements[element][1]}`;
const app=document.querySelector('#app');
let screen='home',mode='bot',team=JSON.parse(localStorage.getItem('pca-team')||'["ember","brook","moss"]'),state=null,you=0,room=null,arena=null,busy=false,botTimer=null,detail=null,showLog=false,showTactics=false,sound=localStorage.getItem('pca-sound')!=='off';
if(team.length!==3||new Set(team).size!==3||!team.every(byId))team=['ember','brook','moss'];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const online=new Online(m=>{if(m.type==='error'){busy=false;toast(m.message);render();}if(m.type==='room'){const prev=state;room=m;you=m.you;state=m.state;screen=state?'battle':'lobby';if(state?.winner!==null&&state)screen='result';busy=false;if(prev&&state&&prev.revision!==state.revision&&arena){const attacker=active(prev,prev.turn),defender=active(prev,1-prev.turn),after=active(state,1-prev.turn);const dealt=Math.max(0,defender.hp-after.hp);const event=dealt?'basic':active(state,prev.turn).id!==attacker.id?'switch':'guard';arena.effect(event,prev.turn===you?0:1,dealt?'−'+dealt+(elementFactor(byId(attacker.id).element,byId(defender.id).element)>1?' ชนะธาตุ!':''):'เข้าสนาม');busy=true;setTimeout(()=>{busy=false;render();},700);}render();}if(m.type==='disconnected'){toast('การเชื่อมต่อหลุด กำลังลองกลับเข้าห้อง');if(room){room.players[you].connected=false;room.players[you].deadline=Date.now()+60000;render();}}if(m.type==='left'){room=null;state=null;screen='home';render();toast('ห้องปิดแล้ว');}});
function toast(message){let t=document.querySelector('#toast');if(!t){t=document.createElement('div');t.id='toast';document.body.append(t);}t.textContent=message;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),3200);}
function tone(){if(!sound)return;try{const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=520;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.18);o.start();o.stop(a.currentTime+.18);o.onended=()=>a.close();}catch{}}
const button=(text,action,cls='',disabled=false)=>{const label={back:'กลับหน้าหลัก',close:'ปิด',sound:sound?'ปิดเสียง':'เปิดเสียง'}[action];return `<button class="${cls}" data-action="${action}" ${label?`aria-label="${label}"`:''} ${action==='sound'?`aria-pressed="${sound}"`:''} ${disabled?'disabled':''}>${text}</button>`;};
function header(title,subtitle=''){return `<header>${button(icon('arrow-left'),'back','back')}<div><h2>${title}</h2><p>${subtitle}</p></div>${button(sound?icon('sound'):icon('sound-off'),'sound','sound')}</header>`;}
function card(c,index,selected=false){return `<button class="pet-card ${c.element} ${selected?'selected':''}" data-action="card:${c.id}"><span class="card-top"><span>${elementHTML(c.element)}</span><small>${c.role}</small></span><img src="${c.image}" alt="${c.name}"><strong>${c.name}</strong><span class="card-bottom">${icon('heart')} ${c.hp} <span>${icon('attack')} ${c.atk}</span></span>${selected?`<b class="pick">${index+1}</b>`:''}</button>`;}
function home(){return `<div class="home"><div class="topline"><span>${icon('sparkle')} LITTLE CREATURES, BIG ADVENTURES</span>${button(sound?icon('sound'):icon('sound-off'),'sound','sound')}</div><div class="brand-icon">${icon('sparkle')}</div><p class="eyebrow">ยินดีต้อนรับสู่ป่าแห่งการ์ด</p><h1>Pocket<br><em>Card Arena</em></h1><p class="intro">เพื่อนตัวจิ๋ว • การต่อสู้ครั้งใหญ่</p><div class="hero"><span class="orbit one">${icon('sparkle')}</span><span class="orbit two">${icon('sparkle')}</span><span class="hero-leaf">${icon('leaf')}</span><img class="hero-side" src="/characters/brook-v2.png" alt="บับเบิลบัน"><img class="hero-main" src="/characters/ember-v2.png" alt="ฟ็อกซ์ฟู"><img class="hero-side right" src="/characters/moss-v2.png" alt="มอสซี่"></div><div class="home-actions">${button(`<span>${icon('attack')}</span><div>เล่นกับบอต<small>ฝึกฝีมือในสนามแห่งป่า</small></div><b>${icon('arrow-right')}</b>`,'bot','primary large')}${button(`<span>${icon('cloud')}</span><div>เล่นกับเพื่อน<small>สร้างห้อง แล้วชวนเพื่อนมาดวล</small></div><b>${icon('arrow-right')}</b>`,'friends','large secondary')}${button(`${icon('collection')} &nbsp; คอลเลกชันการ์ด <small>8 ตัวละคร</small>`,'collection','collection-link')}</div><footer>3 ตัวละคร · 4 ธาตุ · หนึ่งทีมของคุณ<br><span>POCKET CARD ARENA — V1.0</span></footer></div>`;}
function elementLegend(){return `<div class="element-guide"><strong>วงจรชนะธาตุ</strong><div>${icon('fire')} ไฟ <b>${icon('arrow-right')}</b> ${icon('earth')} ดิน <b>${icon('arrow-right')}</b> ${icon('wind')} ลม <b>${icon('arrow-right')}</b> ${icon('water')} น้ำ <b>${icon('arrow-right')}</b> ${icon('fire')} ไฟ</div><small>ชนะ +25% · แพ้ −20% · ธาตุเดียวกัน / คู่ตรงข้าม ดาเมจปกติ</small></div>`;}
function matchup(){const own=byId(active(state,you).id).element,enemy=byId(active(state,1-you).id).element;const factor=elementFactor(own,enemy);return `<div class="element-matchup ${factor>1?'advantage':factor<1?'disadvantage':'even'}"><span>${elementHTML(own)} ${icon('arrow-right')} ${elementHTML(enemy)}</span><strong>${elementMatchupText(own,enemy)}</strong></div>`;}
function collection(){return `${header('คอลเลกชัน','ทำความรู้จักเพื่อนร่วมทีมทั้ง 8 ตัว')}<div class="content">${elementLegend()}<div class="section-label">เพื่อนในป่า <span>8 / 8</span></div><div class="card-grid">${cards.map(c=>card(c)).join('')}</div><div class="hint">แตะการ์ดเพื่อดูค่าสถานะและท่าพิเศษ</div></div>`;}
function teamPage(){return `${header('จัดทีมของคุณ','เลือก 3 ใบไม่ซ้ำ • ใบแรกเป็นตัวเริ่มต้น')}<div class="content"><div class="team-slots">${[0,1,2].map(i=>`<div>${team[i]?`<img src="${byId(team[i]).image}" alt="${byId(team[i]).name}"><strong>${byId(team[i]).name}</strong>${button(i===0?'ตัวเริ่มต้น':'ให้เริ่มก่อน',`starter:${team[i]}`,'tiny')}`:`<span>${icon('plus')}</span><small>เลือกการ์ด</small>`}</div>`).join('')}</div>${elementLegend()}<div class="section-label">เลือกเพื่อนร่วมทีม <span>${team.length} / 3</span></div><div class="card-grid">${cards.map(c=>card(c,team.indexOf(c.id),team.includes(c.id))).join('')}</div><div class="sticky-bottom">${button(mode==='bot'?`เข้าสนาม ${icon('attack')}`:`ยืนยันทีม ${icon('arrow-right')}`,'team-confirm','primary',team.length!==3)}</div></div>`;}
function friends(){return `${header('เล่นกับเพื่อน','ห้องส่วนตัวสำหรับนักเดินทางสองคน')}<div class="content friends"><div class="friend-art"><img src="/characters/mochi-v2.png" alt="โมจิมูน"><span>${icon('cloud')}</span></div><h3>ผจญภัยไปด้วยกัน</h3><p>ทั้งสองคนต้องเชื่อมต่อเซิร์ฟเวอร์เดียวกัน<br>จัดทีมให้พร้อม แล้วพบกันในสนาม</p><label>ชื่อของคุณ<input id="player-name" maxlength="24" placeholder="นักเดินทาง" value="${escape(localStorage.getItem('pca-name')||'')}"></label>${button(`${icon('plus')} สร้างห้องใหม่`,'create','primary')}<div class="divider">หรือเข้าห้องของเพื่อน</div><label>รหัสห้อง<input id="room-code" maxlength="6" placeholder="เช่น A1B2C3" autocomplete="off"></label>${button(`เข้าห้อง ${icon('arrow-right')}`,'join','secondary')}<small class="network-note">ระบบออนไลน์เชื่อมต่อจริงเมื่อสร้างหรือเข้าห้องสำเร็จ</small>${online.session?button('กลับเข้าห้องเดิม','resume','quiet'):''}</div>`;}
function lobby(){return `${header('ห้องของเพื่อน','เลือกทีมและกดพร้อมทั้งสองฝ่าย')}<div class="content lobby"><div class="room-code"><small>รหัสห้อง · ส่งให้เพื่อน</small><strong>${room.code}</strong>${button('คัดลอกรหัส','copy','tiny')}</div>${[0,1].map(i=>{const p=room.players[i];return `<div class="player-row"><span>${i===0?icon('leaf'):icon('cloud')}</span><div><strong>${p?escape(p.name):'รอเพื่อนเข้าห้อง…'} ${i===you?'(คุณ)':''}</strong><small>${p?(p.connected?(p.ready?`พร้อมแล้ว ${icon('check')}`:'กำลังจัดทีม'):'หลุดจากห้อง · รอ 60 วินาที'):'ใช้รหัสด้านบนเพื่อเข้าห้อง'}</small></div><b>${p?.ready?icon('check'):icon('waiting')}</b></div>`;}).join('')}<div class="mini-team">${team.map(id=>`<img src="${byId(id).image}" alt="${byId(id).name}">`).join('')}</div>${button('จัดทีม','edit-team','secondary',room.players[you].ready)}${button(room.players[you].ready?'พร้อมแล้ว • รอเพื่อน':'พร้อมเข้าสนาม','ready','primary',room.players[you].ready)}<p class="hint">ระบบจะสุ่มฝ่ายเริ่มก่อนเมื่อพร้อมทั้งคู่</p></div>`;}
function statusHTML(u){return Object.entries(u.status).map(([k,v])=>`<span title="${statuses[k][1]} เหลือ ${v} เทิร์น" class="status">${icon(statuses[k][0])} ${statuses[k][1]} ${v}</span>`).join('')+(u.charging?`<span class="status charging">${icon('charge')} ชาร์จพร้อมปล่อย</span>`:'')+(u.guard?`<span class="status">${icon('shield')} ตั้งรับ 50%</span>`:'')+(u.shield?`<span class="status">โล่ ${u.shield}</span>`:'');}
function fighter(p,isYou){const player=state.players[p],u=active(state,p),c=byId(u.id);return `<div class="fighter ${isYou?'own':'enemy'}"><div class="fighter-head"><strong>${c.name} <small>${elementHTML(c.element)}</small></strong><span>${isYou?'คุณ':mode==='bot'?'บอต':escape(room.players[p].name)}</span></div><div class="hp-track"><i style="width:${u.hp/c.hp*100}%"></i><b>${icon('heart')} ${u.hp} / ${c.hp}</b></div><div class="fighter-meta"><span class="energy">${icon('energy').repeat(player.energy)}${icon('energy-empty').repeat(6-player.energy)} <b>${player.energy}/6</b></span><small>สลับตัว ${player.switches}/${CONFIG.switches}</small></div><div class="statuses">${statusHTML(u)}</div></div>`;}
function connectionNotice(){if(mode!=='online'||!room)return '';const lost=room.players.find(p=>!p.connected);if(!lost)return '';const seconds=Math.max(0,Math.ceil(((lost.deadline||Date.now()+60000)-Date.now())/1000));return `<div class="connection-notice">${icon('cloud')} ${escape(lost.name)} หลุด • รอกลับเข้าห้อง ${seconds} วินาที</div>`;}
function battle(){const p=state.players[you],a=active(state,you),c=byId(a.id),replace=state.pending===you;const waiting=state.turn!==you||state.pending!==null&&state.pending!==you||mode==='online'&&room.players.some(p=>!p.connected);const disabled=busy||waiting||replace;return `${header('สนามแห่งป่า',`เทิร์น ${state.round} · ${mode==='bot'?'ฝึกฝีมือกับบอต':'ดวลกับเพื่อน'}`)}<div class="battle-content">${connectionNotice()}${fighter(1-you,false)}${tacticalIntentHTML(state,you,mode)}<div class="arena-wrap"><div id="arena"></div><span class="field-tag">${icon('sparkle')} WHISPERING WOODS</span><div class="turn-badge">${replace?'เลือกตัวสำรองลงสนาม':busy?'กำลังใช้สกิล…':waiting?'รอคู่ต่อสู้…':a.status.stun?'คุณติดสตัน • กดเพื่อข้ามแอ็กชัน':'เทิร์นของคุณ • เลือก 1 แอ็กชัน'}</div></div>${fighter(you,true)}${matchup()}${tacticalHUDHTML(state,you)}<div class="battle-controls"><div class="skill-grid">${button(`${icon('attack')}<strong>โจมตี</strong><small>ฟรี • พลัง 100%</small>`,'basic','skill',disabled)}${button(`${icon('shield')}<strong>ป้องกัน</strong><small>${icon('energy')} 1 • รับสำเร็จคืน 1</small>`,'guard','skill',disabled||p.energy<1)}${button(specialButtonHTML(a),'special','skill special',disabled||!a.charging&&(p.energy<c.special.cost||a.cooldown>0))}</div><div class="reserve-label"><span>${replace?'ตัวในสนามหมดสภาพ • เลือกตัวที่ยังมีชีวิต':'ทีมของคุณ • แตะตัวสำรองเพื่อสลับ'}</span><small>${!p.switches&&!replace?'โควตาสลับหมดแล้ว':''}</small></div><div class="reserves">${p.team.map((u,i)=>{const c=byId(u.id);return `<button class="reserve ${i===p.active?'active':''} ${u.hp<=0?'fainted':''}" data-action="swap:${i}" ${busy||(!replace&&(waiting||!p.switches))||i===p.active||u.hp<=0?'disabled':''}><img src="${c.image}" alt="${c.name}"><div><strong>${c.name}</strong><small>${i===p.active?'ในสนาม':u.hp<=0?'หมดสภาพ':replace?'เลือกลงสนาม':'สลับตัว'} · ${u.hp} HP</small><span class="reserve-entry" title="${escape(c.entry.description)}">${icon('switch')} ${c.entry.name}</span><span>${Object.keys(u.status).map(k=>icon(statuses[k][0])).join('')} ${u.charging?icon('charge'):u.cooldown?`${icon('sparkle')} `+u.cooldown:''}</span></div></button>`;}).join('')}</div><div class="battle-last">${escape(state.log.at(-1))}</div><div class="battle-links">${button(`${icon('collection')} วิธีวางแผน`,'tactics','log-button')}${button(`${icon('log')} บันทึกการต่อสู้`,'log','log-button')}</div></div></div>`;}
function result(){const names=mode==='bot'?['คุณ','บอต']:room.players.map(p=>p.name);const win=state.winner==='draw'?'เสมอ!':state.winner===you?'ทีมของคุณชนะ!':'คู่ต่อสู้ชนะ!';return `${header('ผลการแข่งขัน','สรุปผลงานของทั้งสองทีม')}<div class="content results"><span class="trophy">${state.winner===you?icon('trophy'):icon('sparkle')}</span><p class="eyebrow">ARENA COMPLETE</p><h1>${win}</h1><p class="winner-name">${state.winner==='draw'?'ทั้งสองทีมเสมอกัน':'ผู้ชนะ: '+escape(names[state.winner])} · ${state.round} เทิร์น</p>${matchSummaryHTML(state,names,you)}${button('เล่นอีกครั้ง','again','primary')}${button('กลับหน้าหลัก','home','secondary')}${button('ดูบันทึกการต่อสู้','log','quiet')}</div>`;}

function modal(){if(showTactics)return `<div class="modal-backdrop"><div class="modal tactics-modal">${button(icon('close'),'close','modal-close')}${tacticsHelpHTML()}${button('กลับเข้าสนาม','close','primary')}</div></div>`;if(detail){const c=byId(detail);return `<div class="modal-backdrop"><div class="modal">${button(icon('close'),'close','modal-close')}<div class="detail-art ${c.element}"><img src="${c.image}" alt="${c.name}"></div><p class="eyebrow">${elementHTML(c.element)} • ${c.role}</p><h2>${c.name}</h2><p>${c.description}</p><div class="card-element-details"><span>ชนะ ${elementHTML(elementWins[c.element])} • ดาเมจ +25%</span><span>แพ้ ${elementHTML(Object.keys(elementWins).find(k=>elementWins[k]===c.element))} • ดาเมจ −20%</span></div><div class="stats"><span>${icon('heart')} HP <b>${c.hp}</b></span><span>${icon('attack')} ATK <b>${c.atk}</b></span><span>${icon('shield')} DEF <b>${c.def}</b></span></div><div class="skill-detail"><strong>${icon('attack')} โจมตีพื้นฐาน</strong><p>พลัง 100% • ไม่ใช้พลังงาน</p><strong>${icon('shield')} ป้องกัน</strong><p>ลดความเสียหายครั้งถัดไป 50% • พลังงาน 1<br>รับโจมตีสำเร็จได้พลังงานคืน 1</p><strong>${icon('sparkle')} ${c.special.name}</strong><p>พลัง ${Math.round(c.special.multiplier*100)}% • ${statuses[c.special.effect][1]} ${statuses[c.special.effect][2]} เทิร์น<br>พลังงาน 3 • คูลดาวน์ 2 เทิร์น</p></div>${cardTacticsHTML(c)}${button('เข้าใจแล้ว','close','primary')}</div></div>`;}if(showLog)return `<div class="modal-backdrop"><div class="modal">${button(icon('close'),'close','modal-close')}<h2>บันทึกการต่อสู้</h2><ol class="logs">${state.log.map(l=>`<li>${escape(l)}</li>`).join('')}</ol>${button('กลับเข้าสนาม','close','primary')}</div></div>`;return '';}
let renderedScreen=null;
function render(){if(renderedScreen!==screen){window.scrollTo(0,0);renderedScreen=screen;}const wasBattle=screen==='battle'&&arena;if(screen!=='battle'&&arena){arena.destroy();arena=null;}let element;if(wasBattle){element=document.querySelector('.arena-wrap');element?.remove();}app.innerHTML=`<main class="game-shell">${({home,collection,team:teamPage,friends,lobby,battle,result}[screen])()}${modal()}</main>`;if(screen==='battle'){if(element){document.querySelector('.arena-wrap').replaceWith(element);element.querySelector('.turn-badge').textContent=state.pending===you?'เลือกตัวสำรองลงสนาม':busy?'กำลังใช้สกิล…':state.turn===you?'เทิร์นของคุณ • เลือก 1 แอ็กชัน':'รอคู่ต่อสู้…';}else arena=new ArenaView('arena');arena.sync([active(state,you).id,active(state,1-you).id]);scheduleBot();}}
function scheduleBot(){clearTimeout(botTimer);if(mode==='bot'&&screen==='battle'&&!busy&&(state.pending===1||state.pending===null&&state.turn===1)){botTimer=setTimeout(()=>perform(botAction(state,1),1),950);}}
async function perform(action,p=you){if(busy)return;if(mode==='online'){busy=true;render();try{online.send({type:'action',id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,revision:state.revision,action});}catch(e){busy=false;toast(e.message);render();}return;}try{const old=state;const next=act(state,p,action);busy=true;const target=active(old,1-p),after=active(next,1-p);const text=action.type==='basic'||action.type==='special'?`−${Math.max(0,target.hp-after.hp)}${damage(active(old,p),target,1).factor>1?' ชนะธาตุ!':''}`:action.type==='guard'?'ตั้งรับ':'เข้าสนาม';arena?.effect(action.type==='special'&&active(next,p).charging?'guard':action.type,p===you?0:1,action.type==='special'&&active(next,p).charging?'ชาร์จ!':text);tone();render();setTimeout(()=>{state=next;busy=false;if(state.winner!==null)screen='result';render();},700);}catch(e){toast(e.message);}}
async function connectRoom(type){const name=document.querySelector('#player-name')?.value.trim()||'นักเดินทาง';localStorage.setItem('pca-name',name);const code=document.querySelector('#room-code')?.value.trim().toUpperCase();try{if(online.ws?.readyState!==WebSocket.OPEN)await online.connect();online.send(type==='resume'?{...online.session,type:'resume'}:{type,name,code});}catch(e){toast(e.message);}}
app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const [action,arg]=b.dataset.action.split(':');if(action==='sound'){sound=!sound;localStorage.setItem('pca-sound',sound?'on':'off');render();return;}if(action==='close'){detail=null;showLog=false;showTactics=false;render();return;}if(action==='tactics'){showTactics=true;render();return;}if(action==='log'){showLog=true;render();return;}if(action==='card'){if(screen==='team'){if(team.includes(arg))team=team.filter(id=>id!==arg);else if(team.length<3)team.push(arg);else toast('เลือกได้ 3 ใบ • แตะใบที่เลือกเพื่อถอดออก');}else detail=arg;render();return;}if(action==='starter'){team=[arg,...team.filter(id=>id!==arg)];render();return;}if(['basic','guard','special'].includes(action)){perform({type:action});return;}if(action==='swap'){perform({type:state.pending===you?'replace':'switch',index:Number(arg)});return;}if(action==='copy'){try{await navigator.clipboard.writeText(room.code);toast('คัดลอกรหัสแล้ว');}catch{toast(`รหัสห้อง ${room.code}`);}return;}if(action==='ready'){online.send({type:'ready',team});return;}if(['create','join','resume'].includes(action)){connectRoom(action);return;}if(action==='bot'){mode='bot';screen='team';}if(action==='friends'){mode='online';screen='friends';}if(action==='collection')screen='collection';if(action==='edit-team')screen='team';if(action==='team-confirm'){localStorage.setItem('pca-team',JSON.stringify(team));if(mode==='bot'){you=0;state=createMatch([team,['ember','brook','spore']],undefined,{botPlayer:1});screen='battle';}else screen=room?'lobby':'friends';}if(action==='again'){if(mode==='bot'){state=createMatch([team,['ember','brook','spore']],undefined,{botPlayer:1});screen='battle';}else {online.send({type:'rematch'});toast('ส่งคำขอเล่นอีกครั้งแล้ว รอเพื่อน');return;}}if(action==='home'||action==='back'){clearTimeout(botTimer);if(room){online.leave();room=null;}state=null;busy=false;screen='home';}render();});
render();

setInterval(()=>{if(screen==='battle'&&mode==='online'&&room?.players.some(p=>!p.connected))render();},1000);
